
package com.bootdo.gi.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorld", targetNamespace = "http://impl.service.gi.bootdo.com/", wsdlLocation = "http://localhost:80/helloWorld?wsdl")
public class HelloWorld
    extends Service
{

    private final static URL HELLOWORLD_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLD_EXCEPTION;
    private final static QName HELLOWORLD_QNAME = new QName("http://impl.service.gi.bootdo.com/", "HelloWorld");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:80/helloWorld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLD_WSDL_LOCATION = url;
        HELLOWORLD_EXCEPTION = e;
    }

    public HelloWorld() {
        super(__getWsdlLocation(), HELLOWORLD_QNAME);
    }

    public HelloWorld(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLD_QNAME, features);
    }

    public HelloWorld(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLD_QNAME);
    }

    public HelloWorld(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLD_QNAME, features);
    }

    public HelloWorld(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWord
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public HelloWord getHelloWordImplPort() {
        return super.getPort(new QName("http://impl.service.gi.bootdo.com/", "HelloWordImplPort"), HelloWord.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWord
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public HelloWord getHelloWordImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.gi.bootdo.com/", "HelloWordImplPort"), HelloWord.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLD_EXCEPTION!= null) {
            throw HELLOWORLD_EXCEPTION;
        }
        return HELLOWORLD_WSDL_LOCATION;
    }

}
