
package com.bootdo.gi.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bootdo.gi.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWord", targetNamespace = "http://service.gi.bootdo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWord {


    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.gi.bootdo.com/", className = "com.bootdo.gi.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.gi.bootdo.com/", className = "com.bootdo.gi.service.SayHiResponse")
    @Action(input = "http://service.gi.bootdo.com/HelloWord/sayHiRequest", output = "http://service.gi.bootdo.com/HelloWord/sayHiResponse")
    public String sayHi(
            @WebParam(name = "text", targetNamespace = "")
                    String text);

    /**
     * 
     * @param first
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doit", targetNamespace = "http://service.gi.bootdo.com/", className = "com.bootdo.gi.service.Doit")
    @ResponseWrapper(localName = "doitResponse", targetNamespace = "http://service.gi.bootdo.com/", className = "com.bootdo.gi.service.DoitResponse")
    @Action(input = "http://service.gi.bootdo.com/HelloWord/doitRequest", output = "http://service.gi.bootdo.com/HelloWord/doitResponse")
    public String doit(
            @WebParam(name = "first", targetNamespace = "")
                    Integer first);

}
